---
title: "R Notebook"
output: html_notebook
---

```{r}
Inverse_sqrt <- function(x){
  #This function takes one argument x and returns the inverse of its square root.
  return (1/sqrt(x))
}
```
Fibonacci numbers 1; 1; 2; 3; 5; 8; 13; 21; 34; 55;
```{r}
Fibo<- function(n){
  #This function return the n'th Fibonacci number
  a<- 0
  b<- 1
  for(i in 1:n){
    temp <- b
    b <- a
    a <- a+temp
  }
  return(a)
}
```
Fibonacci in recursion form
```{r}
FiboRec <- function(n){
  #This function return the n'th Fibonacci number recursively
  
  #Base Case
  if (n ==0 ||n==1) return(n)
  else return(FiboRec(n-1) + FiboRec(n-2))
}
```
Function application for Maximum Likelihood
```{r}
#setting seed for reproducibility
set.seed(5)
#generating data
mprob <- 0.7 
mydata <- rbinom(100,1,prob = prob)

#exploring data
library(pastecs)
library(psych)
stat.desc(mydata)
describe(mydata)


#log-likelihood for binomial model
MinusBinomLogLik <- function(data, proba){
  result <- 0
  for(i in 1:length(data)){
    result <- result + (data[i] * log(proba) + (1 - data[i]) * log(1 - proba))
  }
  return(-result)
}

#maximize the likelihood to recover the estimated value
optim(par = 0.5, fn = MinusBinomLogLik, data = mydata, method="Brent",
lower=0, upper=1)
```
```{r}
hist(mydata)
```



